# Generated by Django 4.2.3 on 2023-11-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='accounts_action',
            field=models.IntegerField(default=0),
        ),
    ]
